### ISSUE TITLE
Can't access biolisp.org

### ISSUE THREAD

**Issue by azzamsa** [Bohdan-Khomtchouk/Biochat#14] opened 2018-04-01 11:29 UTC
> Or just read the "Why Lisp?" section at: http://biolisp.org

Can't access biolisp.org

**Comment by kasravnd** [comment] 2018-04-01 19:11
@azzamsa  Can you please explain the problem a little bit more? do you get any particular error in response? what kind of browser/platform you're using?

**Comment by Bohdan-Khomtchouk** [comment] 2018-04-01 20:36
@azzamsa That link works for me.  Can you try again and report back?

**Comment by azzamsa** [comment] 2018-04-01 22:40
Oh. I tried to access using chromium and it's fine. But not with Firefox.
I refresh again and again using Firefox but nothing happened.

![2018-04-02-05 37 46](https://user-images.githubusercontent.com/17734314/38178211-0a3b8ffa-3638-11e8-8ae4-5c5fdc2339ec.png)

**Comment by kasravnd** [comment] 2018-04-02 10:42
Please take a look at this link https://support.mozilla.org/en-US/kb/firefox-cant-load-websites-other-browsers-can and let us know if you could resolve the problem.

**Comment by azzamsa** [comment] 2018-04-02 11:25
@kasramvd thank you for the links. It's might be DNS problem or other. The solution either to change the firefox config or  delete the history. I won't change the config nor delete my history.

 I still need all my history cause I haven't move it to my journal.

By the way. I have some alternative. I look at the biolisp.org source code and I can access it well from the github page.

![2018-04-02-18 18 01](https://user-images.githubusercontent.com/17734314/38194674-1e43f7e2-36a3-11e8-8ff2-b73d40e16e7a.png)

**Comment by Bohdan-Khomtchouk** [comment] 2018-04-03 02:22
Closing this issue as resolved.  Since the issue is on Biolisp (not Biochat), please feel free to re-open a ticket there.

**Closed as completed by Bohdan-Khomtchouk** 2018-04-03 02:22 UTC
